### ISSUE TITLE
:jsx.decode/2 is undefined

### ISSUE THREAD

**Issue by bdmac** [bryanjos/joken#139]
After updating:

```
warning: function :jsx.decode/2 is undefined (module :jsx is not available)
  lib/joken/signer.ex:199
```

It looks like you have that defined as only a test dep and jose has that defined as only a dev/test dependency. Doesn't seem like I should need to add that to my mix.deps.

**Comment by cs-victor-nascimento** [comment]
Hi @bdmac!

That is intended. JSX is one of the supported JSON parsers for Joken. The idea is that if you use JSX in your app, we should not force you to use Poison. Because of that, you should explicitly add the dependency you want as a JSON parser and set it in your Joken pipeline.

You are updating from which version? There was a point in time where Joken used Poison only.

**Comment by bdmac** [comment]
Sorry I get it now. I think I just hadn't updated the joken dependency in awhile so it just had not been recompiled. It probably gave the same warning the first time it compiled as well.
