### ISSUE TITLE
Lazy auth

### ISSUE THREAD

**Issue by QuentinFchx** [bryanjos/joken#152]
Hi,

I'd like to implement a lazy auth:
If the user has a token, parse it and set claims, otherwise just move along without failing.
I don't think it's currently doable with the bundled plug.

Do you think it could be part of that lib (through options such as `:joken_skip`)?

**Comment by cs-victor-nascimento** [comment]
Hi @QuentinFchx! I think that in your use case it is best to have an anonymous session than having no authentication at all. This is how, usually, e-commerces implement this feature. 

Otherwise, you could have different routes and skip the one with the current plug. Though this seems more like a workaround. 

If all else fails, you can implement your own plug. It is only one file that depends on Joken. Currently, I don't think that we have the intension of implementing such a feature.

**Comment by aphillipo** [comment]
Write your own plug; it's very simple to do so and it'll be a lot simpler than the Joken.Plug which has a few options.  It doesn't sound like you need the options at all, just to add to assigns[:claims] or not if verify! returns {:okay, token} or {:error, message}.

It's literally just the call function you need to implement.

**Comment by bryanjos** [comment]
I agree. I had conflicted thoughts on this, but I think leaving it out here and defining your own plug in your project using joken to handle the authentication case is a good idea.
