### ISSUE TITLE
I can verify the signature with both private_key and public_key - is this normal?

### ISSUE THREAD

**Issue by AionDev** [bryanjos/joken#179]
I would like to know if it's expected behavior that i'm able to verify something with the `private_key`

```
private_key = JOSE.JWK.from_pem_file("secret/private_key.pem")
my_token =
  %{claim1: "claim1", claim2: "claim2"}
  |> token
  |> with_exp(31_537_000)
  |> with_iat
  |> sign(rs256(private_key))
  |> get_compact

isValid =
  my_token
  |> token
  |> with_validation("claim1", &(&1 == "claim1"))
  |> with_validation("claim2", &(&1 == "claim2"))
  |> with_signer(rs256(private_key))  ---- this works if i use both private_key and public_key..
  |> verify

IO.inspect(isValid)       # %Joken.token{ ... error: nil, errors: [] ... }  
```
From [this security exchange answer](https://security.stackexchange.com/questions/9957/can-i-use-a-private-key-as-a-public-key-and-vice-versa?newreg=dabdf0c0adc54dcda961e1787ce8559c): 

> RSA is a trapdoor permutation which means:
> 
>     If you encrypt with a public key, you can decrypt with the private key.
>     If you encrypt with a private key, you can decrypt with a public key.

Based on this, only the `public_key` should be able to decrypt what was encrypted with the `private_key`
But as shown above, I'm using only the private_key and it works.
Is this normal behavior ?! 🤔   I'm a beginner in this stuff - don't mind me if all this is normal. But just in case is a bug, i think is better to ask. Thanks :)

**Comment by victorolinasc** [comment]
Hey @AionDev ! When it gets down to crypto we are all beginners :) 

Your code works because an RSA private key always "contains" the public key too. If you look [here](http://erlang.org/doc/apps/public_key/using_public_key.html), you will see that the record for the RSA key always contain the public key data.

So, you might ask: why do I need both? 

Well, the use case for JWTs are not for clients to verify signatures. Clients usually just pass the token (and that is another reason why the claims are not encrypted... they can be used without verifying the signature). This might not fit all use cases and if you happen to need another server or party in your system to verify the signature without being able to actually SIGN a new token, then you would give this third party the public key.

This way, they would be able to ensure the token has a proper signature but they would not be able to actually sign a new token.

I'll be closing this as it is the intended way for this to work. Please, feel free to keep asking questions on this thread if you still have doubts. If I can't answer them perhaps someone in the community will :)
