### ISSUE TITLE
Confused about naming the verify callback function on the plug

### ISSUE THREAD

**Issue by raarts** [bryanjos/joken#184]
Hi, I am confused about why the callback function for the Plug is called `verify`.

As I understand it, that function does not actually verify a token, but instead creates more or less a 'template' Joken.Token struct where the incoming token is inserted into, after which it is verified using the (lib internal) `verify/1` function.  This all happens in parse_auth. And then the `evaluate` function is used to get the claims out, and put them in `conn.assigns`.

Is my understanding correct?

Initially looking at the parse_auth function: 

    defp parse_auth(conn, incoming_token) do
      payload_fun = Map.get(conn.private, :joken_verify)

      verified_token = payload_fun.()
      |> with_compact_token(incoming_token)
      |> verify

      evaluate(conn, verified_token)
    end

also confused me because the return value from payload_fun.() is called `verified_token`, which suggests the verification succeeded while the incoming token wasn't even processed yet.

Please note I'm not trying to criticise, but I just want to point out I found this confusing. I also think the `evaluate` function could better be named `save_claims`. Just my $0.02

**Comment by victorolinasc** [comment]
Hi @raarts. Thanks for your feedback.

You are totally right that the current API has some confusion about naming its functions or strategies. We are working on a version update to address all of this. 

The issue arises from constructing the token configuration or accepting a compact token. Since everything is inside the Joken.Token struct and since we have a "token" function things got out of hand. On version 2 we will change this kind of nomenclature to be more explicit. It is still a work in progress but we should release it in a months time.

The thing with the plug though is that there was no way to "carry" a configuration through its lifecycle. Verify actually uses the configuration to verify a token. It throws the config away afterwards. So, it was an approximation. It certainly is not the function that verifies, but it is the function that carries the config to the verify function. Not sure `save_claims` would be a better name here as it is only saved for the life of a connection.  

We hope that with version 2 this gets crystal clear and we will provide better docs too.
