### ISSUE TITLE
verify_and_validate parameter ordering question

### ISSUE THREAD

**Issue by ajkeys** [bryanjos/joken#197]
I'm using 2.0.0-rc2

I did not set any Joken config and my token module is:

```elixir
defmodule MyApp.Token do
  use Joken.Config, default_signer: nil
end
```

I'm needing to dynamically pull the signer so I'm using this code to verify and validate

```elixir
signer = Joken.Signer.create("HS256", dynamic_secret)
{:ok, claims} = MyApp.Token.verify_and_validate(token, signer)
```

The last line fails with `{:error, :empty_signer}`. The explicit signer example in the introduction seems to indicate that I can just do `MyApp.Token.verify_and_validate(token, signer)` but that doesn't seem to work.

I looked into it and saw that the parameter ordering of signer and context is reversed from the order in Joken.verify_and_validate. I don't know which way you want to go, but I wanted to call out the difference. When I changed the function call to `MyApp.Token.verify_and_validate(token, %{}, signer)` it worked fine. My opinion would be to swap the parameters to allow the example to work and bring it in line with Joken.verify_and_validate. If you would like, I can write up a quick pull request to reverse them.

Thanks!

**Comment by victorolinasc** [comment]
Awesome! Thanks!

Yeah this was my bad. In `Joken.verify_and_validate/5` the signer is the third parameter because we need the token config as the first. You are right. I'd appreciate a PR fixing this.

Just to guess are you using it with JWKS? Is that the reason of your dynamic signer? If it is so, I am awaiting for some more feedback to release 2.0 and then release this other library: https://github.com/victorolinasc/joken_jwks which uses a `Joken.Hooks` implementation to fetch the signer. I'm using it and it is working out nicely (still no release because hex don't allow me to depend on a rc version).

**Comment by victorolinasc** [comment]
Thanks for your contribution! 

Please, feel free to give us more feedback on the API and I hope `joken_jwks` works for you too! 

We are thinking about creating an organization to collect projects there like joken, joken_jwks, joken_plug or phoenix and finally a joken_crypto to replace erlang-jose and benefit from a speed bump in the hot path using only built-in algorithm in OTP (like RS***, HS*** JWAs)

Cheers!
