### ISSUE TITLE
potential security issues

### ISSUE THREAD

**Issue by jschoch** [bryanjos/joken#32]
https://www.timmclean.net/2015/03/31/jwt-algorithm-confusion.html

** edited mistakenly assumed :none might match with a signature of "" **
might be nice to be able to ensure :none never will verify :ok so you can prevent the use of :none via Mix.Config or something.

wondering if the other issues in the above article have been considered.

**Comment by cs-victor-nascimento** [comment]
I think we are safe here, but I may be wrong. The problem is that per the
specification, :none is a valid algorithm.

The Joken library is already following the author's advice of using only
one pre-configured algorithm. Its default is HS256 and only if you change
that to none it will end up in that line. The library is not trusting a
user given algorithm but it is checking its own configuration.

In fact, I believe that right now one cannot use the Joken module to
support multiple algorithms (which is good per the author).

If anything other than :none is given in the configuration and even without
telling the configuration which algorithm you would like to use it should
never end on the next line you point.

But I may be missing something OO... Have you figured a way to bypass
verification in Joken?

**Comment by bryanjos** [comment]
@jschoch yes, @cs-victor-nascimento is correct. The algorithm used to verify the token is taken from the config. The alg property on the token is ignored. Using `:none` as the input for the algorithm parameter is used for checking tokens that the user of joken knows doesn't have a signature part.

I followed that exact article actually to fix the algorithm vulnerability. I took a second look just to make sure everything is ok. Thanks for checking to make sure it's secure. If there is anything else you find, please let us know.
