### ISSUE TITLE
:crypto.sha256_mac has new accessor? 

### ISSUE THREAD

**Issue by schainker** [bryanjos/joken#40]
Hi,
After seeing this error, I fired up iex and tried to invoke :crypto.sha256 with no luck. I'm running OTP 17.5 with elixir 1.0.4 on top of that.

`:crypto.hash :sha256, "Hello"` works, however.  I'm not too familiar with Joken or Erlang's crypto library, but is this an issue with the function accessor changing?  Please have a look at the error. I've removed our token string.

```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (crypto) :crypto.sha256_mac_nif(nil, "<<< token string >>> ", 32)
        (crypto) crypto.erl:1029: :crypto.sha256_mac/3
        (joken) lib/joken/token.ex:27: Joken.Token.encode/5
        (phoenix_token_auth) lib/phoenix_token_auth/authenticator.ex:50: PhoenixTokenAuth.Authenticator.generate_unique_token_for/1
        (phoenix_token_auth) lib/phoenix_token_auth/authenticator.ex:42: PhoenixTokenAuth.Authenticator.generate_token_for/1
        (phoenix_token_auth) lib/phoenix_token_auth/users_controller.ex:57: PhoenixTokenAuth.UsersController.confirm/2
        (phoenix_token_auth) lib/phoenix_token_auth/users_controller.ex:1: PhoenixTokenAuth.UsersController.phoenix_controller_pipeline/2
        (echo) lib/phoenix/router.ex:297: Echo.Router.dispatch/2
```

**Comment by bryanjos** [comment]
In iex, try running `:crypto.hmac(:sha256, "secret_key", "string_to_encode")`. If you don't see any errors then that at least means it's nothing with crypto.

**Comment by schainker** [comment]
Works as expected, thanks :)

**Comment by rorymckinley** [comment]
For future generations of internet users who may be trying to google this error - I ran into this error because I had forgotten to set the secret key in the Joken portion of my config:

 # Configure joken                                                                                  
  config :joken,                                                                                     
  json_module: PhoenixTokenAuth.PoisonHelper,                                                        
  algorithm: :HS256,                                             
  secret_key: "Remember to set the secret key"  # Needed to add this element
