### ISSUE TITLE
JWT ID (jti) Claim Check

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/joken#9]

**Comment by bryanjos** [comment]
Would like to know how to handle this. And also if Joken was to create the id, what would be good to use as an id? Or maybe add some way to give it an id generation function to call.

**Comment by cs-victor-nascimento** [comment]
I've been looking for some more info about this. JTI claims usually means you are saving your token to a database because you want to blacklist or revoke them. See the discussion [here](http://stackoverflow.com/questions/28907831/how-to-use-jti-claim-in-a-jwt) for example.

In an [article from Auth0](https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/) it seems like they are using SHA-1 to hash some opaque value. I am using UUIDs and am trying to find out if that is a bad idea...

IMHO Joken doesn't have much to do here besides illustrating some usage. Actually I think a lot of people are not too sure about the best workflow with tokens. It would be useful to have some articles in the wiki with guidance in how to implement a proper flow with JWTs. Maybe some references only but I think some sample code of use cases could help a lot.

**Comment by bryanjos** [comment]
I'm not sure what is correct for the value. I think anything is fine as long as their is some expectation of uniqueness. This is one of the use cases that #26 would cover pretty well and let the user of joken figure out what to use as the id and how to validate it.

Adding some information on JWTs would be helpful. I'm not exactly an expert in best practices on JWT. I've looked over the spec a couple of times to make sure I'm following it here. I can add some examples for Joken. If you have anything to add as well that would be helpful
